### PR TITLE
Add dreamwalk

### PR DESCRIPTION
**Pull request by adriaque**
This pull request adds the DreamWalk algorithm in the analyzer part of pyBiodataFuse. Contains two folders:

- **DreamWalk/dreamwalk**: here the algorithm files are stored
- **DreamWalk/Use case:** contains the list of input genes for generating the post-COVID-19 graph, the actual graph, an example script of how to run the algorithm and the result models of the algorithm.

### CODE REVIEW

**Comment by YojanaGadiya** [comment]
@tabbassidaloii when you check for Minvera, please look at this PR too. It seems there are some files edited too in this branch.

**Comment by YojanaGadiya** [comment]
Also, it doesn't make sense to clone the whole repo in here. Rather we direct people to clone the package in the env and then run the code.

**Comment by tabbassidaloii** [comment]
@YojanaGadiya would conda recipes be a solution to avoid cloning the repo?

**Comment by YojanaGadiya** [comment]
@tabbassidaloii I can basically create a package of it, but I don't want to since I am not the owner and there might then be issues. I remember you talking about generating a docker image of this package and adding the docker file in the repo for usage.. maybe you can direct me to some work that you saw and I can take a look

**Comment by tabbassidaloii** [comment]
@YojanaGadiya not sure if docker is the solution, I just asked someone
We should look for other ways, 
maybe contacting them and share our interest in including their algorithm in BDF?

**Comment by YojanaGadiya** [comment]
Based on discussion on 12th April, this will no longer be part of BDF.

**Pull request closed without merging**
