### PR TITLE
collapse_data_source method fixed

### PR DESCRIPTION
**Pull request by DominikMartinat**
method now drops rows with duplicate identifiers and duplicate body response

in case of duplicate identifiers where one response is empty, keeps only row with non-empty response

there has been no rows with duplicate identifier and non-duplicate non-empty response found yet, but might need to solve it later

### CODE REVIEW

**Comment by tabbassidaloii** [comment]
@DominikMartinat I think that it would be better to fix this in the relevant annotators, as the number of columns might not be the same across different annotators. (L92: columns[4:])

**Comment by DominikMartinat** [comment]
@tabbassidaloii I know. This way it works with 4 or more columns. First four are for the mapping data frame frome BridgeDB. The rest is output from database query. But I can fix it in annotator itself too.

**Comment by tabbassidaloii** [comment]
The output of BridgeDb does not always have 4 columns. Now we also support the differential expression table, meaning that the input has multiple columns and therefore, the BridgeDb file would have more than 4 columns

**Comment by DominikMartinat** [comment]
Ah I understand now. Thanks for explanation. I will fix it in annotator then.

**Comment by tabbassidaloii** [comment]
> Ah I understand now. Thanks for explanation. I will fix it in annotator then.

@DominikMartinat Thank you too :) 
I think implementing the drop before merging would make more sense. I mean dropping the duplication in the query output.

**Pull request merged**
